### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by Razuuu** [Maxopoly/Angelia-cmd#3]
timolia.de
[22:35:44 ERROR]: Could not connect to server
java.io.IOException: Failed to connect to timolia.de:25565
	at com.github.maxopoly.angeliacore.connection.ServerConnection.reestablishConnection(ServerConnection.java:122) ~[Angelia-cmd.jar:?]
	at com.github.maxopoly.angeliacore.connection.ServerConnection.connect(ServerConnection.java:150) ~[Angelia-cmd.jar:?]
	at com.github.maxopoly.angeliacore.connection.ActiveConnectionManager.initConnection(ActiveConnectionManager.java:29) [Angelia-cmd.jar:?]
	at com.github.maxopoly.angelia_cmd.Main.main(Main.java:24) [Angelia-cmd.jar:?]
[22:35:44 INFO]: Autoreconnecting is disabled, connection will remain closed

**Comment by Maxopoly** [comment]
Are you using the latest version?

**Comment by Razuuu** [comment]
yes
